### ISSUE TITLE
[UWP] IsPlaying=true does not play the animation

### ISSUE THREAD

**Issue by MattRames** [martijn00/LottieXamarin#270] opened 2020-05-11 17:10 UTC
## 🐛 Bug Report

The following AnimationView does not play in the sample app.

```
<forms:AnimationView x:Name="animationView"
                     Grid.Row="1"
                     Animation="LottieLogo1.json"
                     HorizontalOptions="FillAndExpand"
                     IsPlaying="True"
                     Loop="True"
                     VerticalOptions="FillAndExpand" />
```

### Expected behavior

I would expect the animation to play if IsPlaying is set to true. This is the behavior on Android and iOS.

### Reproduction steps

Replace the animation view in the sample app with the xaml above.

### Configuration

**Version:** 3.1.2

**Platform:** 
- [ ] :iphone: iOS
- [ ] :robot: Android
- [ ] :checkered_flag: WPF
- [x] :earth_americas: UWP
- [ ] :apple: MacOS
- [ ] :tv: tvOS
- [x] :monkey: Xamarin.Forms

**Comment by ckrempp91** [comment] 2020-05-14 15:01
I have found the problem it seems that in the native UWP Play function in the AnimationViewRenderer has an assignment for Element.IsPlaying = true. This is causing the binding mechanism from accepting updates. I can not create a branch or PR so I could not upload the change myself. I was able to pull down the source and get the sample to work properly.

I believe this is also why issue [[UWP] PlayFrameSegment and PlayProgressSegment Only Work In Reverse #269](https://github.com/Baseflow/LottieXamarin/issues/269) is having a problem as well.

**Comment by MattRames** [comment] 2020-05-14 15:56
@ckrempp91 Did you just remove the assignment in OnPlay(...) and PrepareReverseAnimation(...)? I don't have time to debug at the moment but I may give it a go over the weekend.

**Comment by ckrempp91** [comment] 2020-05-14 16:10
No just this line here: https://github.com/Baseflow/LottieXamarin/blob/f0ef94dc90223b6cb3a8770b4d8f42aad3962442/Lottie.Forms/Platforms/Uap/AnimationViewRenderer.cs#L248

**Comment by MattRames** [comment] 2020-05-17 21:56
Still no luck with having the animation play removing that line. Did you change anything else?

https://github.com/MattRames/LottieXamarin/commit/9ed018d246212699e750cdd3b0f04672149ad08e

**Comment by ckrempp91** [comment] 2020-05-18 15:00
No, that is the only line that I changed. Here is a sample of my debug execution:

![Debug Sample](https://user-images.githubusercontent.com/15944499/82227020-d9ae3d00-98ec-11ea-8787-f0c78cfef6a1.gif)

I am not sure if maybe there is a version difference between our development environments:
[Visual Studio Info](https://github.com/Baseflow/LottieXamarin/files/4644818/VS_Info.txt)

Windows SDK Versions installed:
![SDK Version](https://user-images.githubusercontent.com/15944499/82227637-acae5a00-98ed-11ea-8718-b906aeb4c711.png)

Pressing the "Play" button sends the binding update for the IsPlaying property to be set to true. The "Pause" button sets the IsPlaying property to false. 

Is the expectation to have the animation to play automatically when the view is displayed? If so I think this issue should be adjusted to reflect that.

**Comment by MattRames** [comment] 2020-05-18 15:05
It works fine when using a binding. It doesn't work when using the xaml above in the OP, which doesn't use the binding.

**Comment by ckrempp91** [comment] 2020-05-18 16:09
I apologize for my misunderstanding about the binding approach. (I do think that assignment of the IsPlaying property should still be removed from the native Play function though) 

After testing with the above XAML I was able to reproduce the issue in the OP, and believe the issue is due to this: [AnimatedVisualPlayer::PlayAsync should internally wait for the AnimatedVisual to load instead of silently failing](https://github.com/microsoft/microsoft-ui-xaml/issues/1484) which mentions that the underlying AnimatedVisualPlayer does not play the animation correctly when it has not completely loaded.

With this in mind I ran a test to add an event to the Loaded eventhandler with a small delay and the animation works when opening. Here is the code I used for the Loaded event:
```
private async void _animationView_Loaded(object sender, Windows.UI.Xaml.RoutedEventArgs e)
{
#pragma warning disable CS0618 // Type or member is obsolete
    if (Element.AutoPlay || Element.IsPlaying)
#pragma warning restore CS0618 // Type or member is obsolete
    {
        await Task.Delay(1000);
        await _animationView.PlayAsync(0, 1, Element.Loop).AsTask();
     }
     else
     {
         _animationView.Stop();
     }
}
```

I then just removed the IsPlaying check from the OnElementChanged override function and attached the Loaded event to the _animationView when the native control is being created:
```
if (Control == null && e.NewElement != null)
{
    _animationView = new AnimatedVisualPlayer { AutoPlay = false };
    _animationView.Loaded += _animationView_Loaded;
    SetNativeControl(_animationView);
}
```

**Comment by ckrempp91** [comment] 2020-05-22 23:21
@MattRames after thinking about this some more I think the best option would be to create a `On` setting of the delay. This would prevent from having to add a properly unique to only 1 platform and can allow users to adjust the delay to what they need. The default can be 1000 milliseconds. I will see if I have any time over the weekend to get a sample of the `On` functionality working.

**Comment by ckrempp91** [comment] 2020-06-11 21:28
@MattRames I apologize for the delay, but I have a working sample with using platform specifics of the `On` class with the LottieXamarin -> Example.Forms.UWP project. 

I added a property called `DelayBeforeLoadMilliseconds` to contain the delay (in milliseconds) for the `AnimatedVisualPlayer` to wait within the `Loaded` event before calling the `PlayAsync` function. If nothing is set then the default is 1000. Based upon testing 1 second was sufficient enough to get the sample to work, but it may depend upon the lottie resource being attempted to play.

Here is the list of files that were modified:
Changed:
- Lottie.Forms\Platforms\Uap\AnimationViewRenderer.cs
  - Added event handler to the `Loaded` event of the `AnimatedVisualPlayer` so that we can add a desired delay before the `PlayAsync` function is executed. Since it was found that performing the play before the player is ready will result in the animation not appear to work at all.
  - You will notice at line 86 the use of the `DelayBeforeLoadMilliseconds` which is get/set via the `On` configuration for the `Windows` configuration
- Lottie.Forms\AnimationView.cs
  - Extended the class to use the `IElementConfiguration<AnimationView>` interface to allow the `On` functionality to work with the view.
  -  You will notice a new class at the bottom called `PlatformConfigurationRegistry` because in the Xamarin.Forms source it was found to have an internal visibility so I could not use it directly and had to copy the structure for this use case.
- Samples\Forms\Example.Forms\MainPage.xaml
  - I set the `Loop` and `IsPlaying` properties to true to match the conditions of the original problem
- Samples\Forms\Example.Forms\MainPage.xaml.cs
  - Within the constructor you will notice the invocation of the `On` to set the platform specific rule of the `DelayBeforeLoadMilliseconds` for the `Windows` configuration.

Added:
- Lottie.Forms\PlatformSpecifics\Uap\AnimationViewExtensions.cs
  - This class offers the functions for the `On` operation to work similar to how other Xamarin Forms controls are structured.

NOTE - I had to cut our the .git folder to get this to compress small enough other wise I would refer to you review that for the changes.

[LottieXamarin - Example.zip](https://github.com/Baseflow/LottieXamarin/files/4767349/LottieXamarin.-.Example.zip)

Let me know what you think, and I am up for any name changes or adjustments.

**Comment by velocitysystems** [comment] 2020-06-24 14:54
Just wondering if there is any ETA for resolving this?

Unfortunately, the updated version of `LottieXamarin` using the `Microsoft.Toolkit.Uwp.UI.Lottie` isn't in good shape on UWP. I see there was a recent commit to fix the path issue, just wondering if a new package will be released soon?

In the meantime, we're forced to fix the issues through a custom renderer.

**Comment by martijn00** [comment] 2020-09-09 13:51
Try 4.0, there it works

**Closed as completed by martijn00** 2020-09-09 13:51 UTC
