### ISSUE TITLE
Nugets and .Net Maui

### ISSUE THREAD

**Issue by frankd1996** [martijn00/LottieXamarin#369] opened 2022-01-08 20:40 UTC
Hello, my name is Frank, I am a software developer with Xamarin Forms and I use several of their tools, such as XF.Material and LottieXamarin. They are great!
But I would like to know if these tools will be available in .Net Maui and if a migration of them will be possible. If so, do you have an estimated date when this is possible? Greetings.

**Comment by nodoid** [comment] 2022-01-11 21:29
Dupe of #363

**Closed as completed** 2022-01-31 09:34 UTC
